language: python
python:
  - '2.7'
sudo: required
install:
  - source cfg4dev
  - pip install coveralls
  - node -v
  # these next 2 lines should not be required (added 12 Mar '16) ...
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - node -v
  - which node
  - sudo apt-get install -y nodejs
  - node -v
  - which node
  - . ~/.nvm/nvm.sh
  - nvm install 4.1.0
  - which node
  - node -v
  - npm i -g raml2md
  - npm i -g raml2html
script:
  - pep8
  - flake8
  - tor_async_util_nosetests.py -A "not integration" --with-coverage --cover-branches --cover-erase --cover-package ecs
  - coveralls || true
  - python setup.py sdist --formats=gztar
  - ./api_docs/build-api-docs.sh -t
#  - ./dockerfiles/build-docker-images.sh $DOCKER_EMAIL $DOCKER_USERNAME $DOCKER_PASSWORD ./dist/ecs-*.*.*.tar.gz ./api_docs/api_docs.tar
