language: python
python:
  - '2.7'
sudo: required
install:
  - source cfg4dev
  - pip install coveralls
  # per https://github.com/travis-ci/travis-ci/issues/4090
  # travis does not support more than one language declaration
  # and hence the need to nvm install 4.1.0 of node below
  - nvm install 4.1.0
  - npm i -g raml2md
  - npm i -g raml2html
script:
  - pep8
  - flake8
  - tor_async_util_nosetests.py -A "not integration" --with-coverage --cover-branches --cover-erase --cover-package ecs
  - coveralls || true
  - python setup.py sdist --formats=gztar
  - ./api_docs/build-api-docs.sh -t
#  - ./dockerfiles/build-docker-images.sh $DOCKER_EMAIL $DOCKER_USERNAME $DOCKER_PASSWORD ./dist/ecs-*.*.*.tar.gz ./api_docs/api_docs.tar
