language: python
python:
  - '2.7'
sudo: required
dist: trusty
install:
  - source cfg4dev
  - pip install coveralls
  - nvm install 4.1.0
  - npm i -g raml2md
  - npm i -g raml2html
  - sudo apt-get install -y docker.io
  - sudo sed -i -e 's|DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock"|DOCKER_OPTS="-H tcp://172.17.42.1:2375 -H unix:///var/run/docker.sock"|g' /etc/default/docker
  - sudo service docker restart
script:
  - pep8
  - flake8
  - tor_async_util_nosetests.py --with-coverage --cover-branches --cover-erase --cover-package ecs
  - coveralls || true
  - tests/load/run_load_test.sh -v
  - python setup.py sdist --formats=gztar
  - ./api_docs/build-api-docs.sh -t
  - ./dockerfiles/build-docker-images.sh ./dist/ecs-*.*.*.tar.gz ./api_docs/api_docs.tar $DOCKER_USERNAME $DOCKER_EMAIL $DOCKER_PASSWORD
