language: python
python:
  - '2.7'
install:
  - source cfg4dev
  - pip install coveralls
  - npm i -g raml2md
#  - npm i -g raml2html
script:
  - pep8
  - flake8
  - tor_async_util_nosetests.py -A "not integration" -A "not sanity" --with-coverage --cover-branches --cover-erase --cover-package ecs
  - coveralls
  - python setup.py sdist --formats=gztar
#  - ./api_docs/build-api-docs.sh -t
#  - ./dockerfiles/build-docker-images.sh $DOCKER_EMAIL $DOCKER_USERNAME $DOCKER_PASSWORD ./dist/ecs-*.*.*.tar.gz ./api_docs/api_docs.tar
